Manero/Controllers/MyPromocodesAddController.cs
using Manero.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Manero.Controllers
{
    public class MyPromocodesAddController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(MyPromoViewModel model)
        {  
            return RedirectToAction("index", "Mypromocodes", model);
        }
    }
}

Manero/Controllers/MyPromocodesController.cs
using Manero.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Manero.Controllers
{
    public class MyPromocodesController : Controller
    {
        public IActionResult ClonePartial1(MyPromoViewModel model)
        {
            var clonedModel = new MyPromoViewModel
            {
                CompanyName_1 = model.CompanyName_1,
                DiscountPercentage_1 = model.DiscountPercentage_1,
                Month_1 = model.Month_1,
                VaildYear_1 = model.VaildYear_1
            };

            clonedModel.GenerateRandomCompanyName();
            clonedModel.GenerateRandomDiscountPercentage();
            clonedModel.GenerateRandomValidYearAndMonth();
            return PartialView("/Views/Partials/_MyPromocodesPartial_1.cshtml", clonedModel);
        }

        public IActionResult ClonePartial2(MyPromoViewModel model)
        {
            var clonedModel = new MyPromoViewModel
            {
                CompanyName_2 = model.CompanyName_2,
                DiscountPercentage_2 = model.DiscountPercentage_2,
                Month_2 = model.Month_2,
                VaildYear_2 = model.VaildYear_2
            };

            clonedModel.GenerateRandomCompanyName();
            clonedModel.GenerateRandomDiscountPercentage();
            clonedModel.GenerateRandomValidYearAndMonth();
            return PartialView("/Views/Partials/_MyPromocodesPartial_2.cshtml", clonedModel);
        }

        public IActionResult ClonePartial3(MyPromoViewModel model)
        {
            var clonedModel = new MyPromoViewModel
            {
                CompanyName_3 = model.CompanyName_3,
                DiscountPercentage_3 = model.DiscountPercentage_3,
                Month_3 = model.Month_3,
                VaildYear_3 = model.VaildYear_3
            };

            clonedModel.GenerateRandomCompanyName();
            clonedModel.GenerateRandomDiscountPercentage();
            clonedModel.GenerateRandomValidYearAndMonth();
            return PartialView("/Views/Partials/_MyPromocodesPartial_3.cshtml", clonedModel);
        }

        public IActionResult Index(MyPromoViewModel model)
        {

            // Generate new promocode temporarily
            model.GenerateRandomCompanyName();
            model.GenerateRandomDiscountPercentage();
            model.GenerateRandomValidYearAndMonth();
            return View(model);
        }
    }
}

Manero/Views/MyPromocodesAdd/Index.cshtml
<section class="section-mypromocodes">
    <div class="container">
        <div class="header-mypromocodes">
            <a asp-controller="profilepage"><i class="fa-solid fa-chevron-left"></i></a>
            <h1>My Promocodes</h1>
        </div>
    </div>
    <div class="d-flex justify-content-center mt-4 mb-3"><img src="/images/page33-promocodeAdd.png" alt=""></div>
    <div class="d-flex justify-content-center mb-2"><div class="order-line"></div></div>
    <h1 class="h1-promocodes">Your dont have</h1>
    <h1 class="h1-promocodes">promocodes</h1>
    <h1 class="h1-promocodes mb-2">yet!</h1>
    <p class="text-center px-5">Qui ex aute ipsum duis. Incididunt adipisicing voluptate laborum</p>

    <div class="d-grid justify-content-center promocodes-label-setup">
        <p>ENTER THE VOUCHER</p>
        <form asp-controller="MyPromocodes" asp-action="Index" method="post">
            <label class="d-grid" for="">
                <input type="text" name="promocode" placeholder="Promocode2022">
                <button type="submit" class="mt-3 button-theme">Submit</button>
            </label>
        </form>
    </div>

</section>